### ISSUE TITLE
Build fails with boost 1.55

### ISSUE THREAD

**Issue by arcke** [InvictusInnovations/keyhotee#35]
While building Keyhotee on Arch Linux with the new boost 1.55 installed the build fails.

<pre><code>https://github.com/InvictusInnovations
https://github.com/InvictusInnovations/BitShares
https://github.com/InvictusInnovations/keyhotee
https://github.com/InvictusInnovations/fc

git clone Keyhotee
cd keyhotee
git clone bitshares
cd bitshares
git clone fc

cd ..
cd ..

cmake .

make

...

In file included from /usr/include/boost/atomic/detail/platform.hpp:22:0,
                 from /usr/include/boost/atomic/atomic.hpp:17,
                 from /usr/include/boost/atomic.hpp:12,
                 from /usr/include/boost/thread/pthread/once_atomic.hpp:20,
                 from /usr/include/boost/thread/once.hpp:20,
                 from /usr/include/boost/thread.hpp:17,
                 from /home/arcke/src/keyhotee/BitShares/fc/src/thread/thread_d.hpp:4,
                 from /home/arcke/src/keyhotee/BitShares/fc/src/thread/thread.cpp:5:
/usr/include/boost/atomic/detail/gcc-atomic.hpp: In member function ‘void fc::thread_d::process_tasks()’:
/usr/include/boost/atomic/detail/gcc-atomic.hpp:1081:95: error: invalid memory model for ‘__atomic_exchange’
         return __atomic_exchange_n(&v_, v, atomics::detail::convert_memory_order_to_gcc(order));
                                                                                               ^
BitShares/fc/CMakeFiles/fc.dir/build.make:149: recipe for target 'BitShares/fc/CMakeFiles/fc.dir/src/thread/thread.cpp.o' failed</code></pre>

Possibly relevant Git revision:
https://github.com/boostorg/atomic/commit/822d7655cfb533e1716ceb157ce95ba2a5c113e2#diff-c2ccfeb733c2452f2d782c2b343b6628

Possibly relevant SVN changeset:
https://svn.boost.org/trac/boost/changeset/85092

For further reference:
https://bitsharestalk.org/index.php?topic=15.msg13715#msg13715
https://bitsharestalk.org/index.php?topic=15.msg13778#msg13778

**Comment by dnotestein** [comment]
We're working with Boost 1.53. If you want, you can make the necessary modifications to also support 1.55 (maybe with some ifdefs if necessary) and I can merge a pull request for you, but we don't have time to look at this at Invictus right now.

**Comment by arcke** [comment]
For a possible solution see: https://bitsharestalk.org/index.php?topic=15.msg14109#msg14109

**Comment by dnotestein** [comment]
Ok, after some analysis, I pushed a fix based on arcke's suggestion above. I can't duplicate the problem here since I'm using 1.53, so please pull and compile and close this issue if it resolves it.
