### ISSUE TITLE
advice:rename vCard to vcard

### ISSUE THREAD

**Issue by vipjeffreylee** [InvictusInnovations/keyhotee#300]
[ 69%] Building CXX object CMakeFiles/Keyhotee.dir/AddressBook/ContactvCard.cpp.o
In file included from /home/jeffrey/Git/keyhotee/AddressBook/ContactvCard.cpp:1:0:
/home/jeffrey/Git/keyhotee/AddressBook/ContactvCard.hpp:3:25: fatal error: vcard/vcard.h: No such file or directory
 #include "vcard/vcard.h"

**Comment by dnotestein** [comment]
Code currently doesn't compile because of a bad merge conflict that occurred with git. It's a known issue, will hopefully be resolved tomorrow.

**Comment by dnotestein** [comment]
Well, actually above comment is not true, looks like merge conflict is already fixed. I've committed a quick fix for the include by using vCard instead of vcard: https://github.com/InvictusInnovations/keyhotee/commit/8eb1733d9e4f19a019da24a73e3f68e2ed792d85
